### ISSUE TITLE
Rest error text-list.spec.js

### ISSUE THREAD

**Issue by pluxuryprince** [Shyam-Chen/Backend-Starter-Kit#1]
Hello, first of all thank you for posting this boilerplate 👍 

Every installation of the boilerplate occurred successfully however when starting the project with the `sudo yarn start`. I'm getting several errors of the `test/rest/text-list.spec.js` and `/__/list/relational`, I was checking the commits sent by you and I realized that a large part of his `CircleCI Builds` occurring normally and without error.

Could you explain why I'm having these mistakes?

My **changelog** of build send to **CircleCI**.

```
#!/bin/bash -eo pipefail
docker-compose exec api yarn unit
yarn run v1.3.2
$ jest --coverage --forceExit
Determining test suites to run...

 RUNS  ...

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

 RUNS  ...


 RUNS  ...

(node:68) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

 RUNS  ...


 RUNS  ...

GET /__/list 200 - - 612.198 ms
GET /__/list/count 200 2 - 48.484 ms
GET /__/list?_id=59901c7dbc9187001ec32c7b 200 2 - 24.497 ms

 RUNS  ...

GET /__/list?text=v 200 2 - 15.068 ms
GET /__/list/pagination/2/5 200 378 - 69.153 ms

 RUNS  ...

POST /__/list 200 24 - 34.436 ms
PUT /__/list/59901c7dbc9187001ec32c7b 200 26 - 34.519 ms
DELETE /__/list/59901c7dbc9187001ec32c7b 200 26 - 15.032 ms

 RUNS  ...

 FAIL  test/rest/text-list.spec.js

 RUNS  ...

  ● Console

    console.log src/api.js:70
       [*] App: Bootstrap Succeeded.
    console.log src/api.js:71
       [*] Host: http://localhost:3000/.
    console.log src/api.js:107
       [*] Redis: Connection Succeeded.
    console.log src/api.js:86
       [*] Postgres: Connection Succeeded.
    console.log src/api.js:78
       [*] Mongo: Connection Succeeded.
    console.log node_modules/sequelize/lib/sequelize.js:1062
      Executing (default): INSERT INTO "Lists" ("id","text","createdAt","updatedAt") VALUES (DEFAULT,'Web GO','2017-11-26 15:16:26.822 +00:00','2017-11-26 15:16:26.822 +00:00') RETURNING *;
    console.log node_modules/sequelize/lib/sequelize.js:1062
      Executing (default): SELECT "id", "text", "createdAt", "updatedAt" FROM "Lists" AS "List";


 RUNS  ...

  ● REST › should POST /__/list/relational

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      200
    Received:
      500
      
      at Object.it (test/rest/text-list.spec.js:78:24)
          at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  ● REST › should GET /__/list/relational

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      200
    Received:
      500
      
      at Object.it (test/rest/text-list.spec.js:86:24)
          at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)


 RUNS  ...


 RUNS  ...


 RUNS  ...

POST /__/list/relational 500 - - 152.110 ms
GET /__/list/relational 500 - - 17.545 ms

 RUNS  ...

 PASS  test/graphql/text-list.spec.js

 RUNS  ...


Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 failed, 9 passed, 11 total
Snapshots:   0 total
Time:        3.95s
Ran all test suites.
-------------------|----------|----------|----------|----------|----------------|
File               |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------|----------|----------|----------|----------|----------------|
All files          |     55.6 |    35.94 |    41.67 |       60 |                |
 src               |       76 |    59.09 |    44.44 |    85.71 |                |
  api.js           |    72.09 |       50 |    44.44 |    82.86 |... 63,87,98,99 |
  config.js        |      100 |    64.29 |      100 |      100 |      3,5,6,8,9 |
 src/document      |    43.33 |        0 |        0 |       50 |                |
  authorization.js |    39.29 |        0 |        0 |    45.83 |... 44,45,51,52 |
  index.js         |      100 |      100 |      100 |      100 |                |
  text-list.js     |      100 |      100 |      100 |      100 |                |
 src/graphql       |    18.75 |        0 |      100 |       20 |                |
  authorization.js |    66.67 |      100 |      100 |    66.67 |             18 |
  index.js         |      100 |      100 |      100 |      100 |                |
  text-list.js     |     7.41 |        0 |      100 |        8 |... 88,89,90,92 |
 src/relational    |    93.33 |       75 |      100 |    93.33 |                |
  authorization.js |      100 |      100 |      100 |      100 |                |
  index.js         |    90.91 |       75 |      100 |    90.91 |             19 |
  text-list.js     |      100 |      100 |      100 |      100 |                |
 src/rest          |    55.26 |    26.92 |    37.93 |    58.82 |                |
  authorization.js |    19.05 |        0 |        0 |    23.53 |... 57,62,63,64 |
  email.js         |    22.22 |        0 |        0 |       25 |... 17,19,20,21 |
  index.js         |      100 |      100 |      100 |      100 |                |
  text-list.js     |    83.05 |     87.5 |    91.67 |    82.14 |... 151,153,165 |
-------------------|----------|----------|----------|----------|----------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

Thanks ❤️

**Comment by Shyam-Chen** [comment]
Restart it?

**Comment by Shyam-Chen** [comment]
No message here!
